package com.robosoft.elearning.modal;

public enum ContentType {
    IMAGE,
    VIDEO,
    AUDIO,
    IMAGEWITHVIDEO,
    IMAGEWITHAUDIO,
    IMAGEWITHINFO,
    VIDEOWITHAUDIO,
    VIDEOWITHINFO,
    AUDIOWITHINFO,
    IMAGEWITHVIDEOAUDIO,
    IMAGEWITHVIDEOINFO,
    IMAGEWITHAUDIOINFO,
    VIDEOWITHAUDIOINFO,
    IMAGEVIDEOAUDIOINFO,
    INFO

}

