package com.robosoft.elearning.modal;

public enum ContentType {
    IMAGE,
    VIDEO,
    AUDIO,
//    audio,
//    IMAGEWTHINFO,
    IMAGEWITHVIDEO,
    IMAGEWITHAUDIO,
    IMAGEWITHINFO,
    VIDEOWITHAUDIO,
    VIDEOWITHINFO,
    AUDIOWITHINFO,
    AUDIOWITHIMAGE,
    AUDIOWITHVIDEO,
    IMAGEWITHVIDEOAUDIO,
    IMAGEWITHVIDEOINFO,
    IMAGEWITHAUDIOINFO,
    VIDEOWITHAUDIOINFO,
    IMAGEVIDEOAUDIOINFO,
    INFO

}

