spring.application.name=elearning

spring.datasource.url=jdbc:mysql://${AWS_RDS_HOST}:3306/e-learning_db
#spring.datasource.url=jdbc:mysql://localhost:3306/e-learning_db1
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
#
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#logging.level.org.hibernate.SQL=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.redis.host=localhost
#spring.redis.port=6379
#spring.redis.timeout=10000

#spring.redis.ssl=true
#spring.redis.host=redis-10952.crce179.ap-south-1-1.ec2.redns.redis-cloud.com
#spring.redis.port=6379
#spring.redis.password=d3gVBr6m4JFUdnpAWr5NAmteP1AS7qBE
#spring.redis.timeout=10000

spring.redis.host=${REDIS_HOST}
#spring.redis.port=10952
spring.redis.port=13643
spring.redis.ssl=true
spring.redis.password=${REDIS_PASSWORD}
spring.redis.timeout=10000


aws.access.key.id=${AWS_ACCESS_KEY}
aws.secret.access.key=${AWS_SECRETE_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket.name=${AWS_BUCKET_NAME}

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spring.app.jwtSecret=${JWT_SECRETE}
#spring.app.jwtAccessExpirationMs=900000
spring.app.jwtAccessExpirationMs=90000000
spring.app.jwtRefreshExpirationMs=604800000

mail.registration.subject=Your OTP for Registration
mail.registration.content=Use the following OTP to complete your registration:

email.already.exist.message=The email is already register
token.blacklistedMessage=Please login
success.logout.message=Successfully Logged out
success.passwordUpdated.message=Successfully updated the password
mail.registration.success.subject=Registration Successful
mail.registration.success.content=Thanks for registering to our E-Learning app.


mail.changePassword.subject=Password Reset OTP
mail.changePassword.content=Your OTP for resetting the password is:
message.otpSend.success=OTP sent successfully to your email
spring.config.import=optional:classpath:application-secret.properties

subject.success.fetch-all=All subjects fetched successfully.
subject.success.fetch-by-topicId=Subject fetched successfully.

message.error.userNotFound=User Not Found
subject.error.not-found=Subject not found.
content.error.not-found=Content not found.
lesson.error.not-found=Lesson not found.
topic.error.not-found=Topic not found.
notification.error.not-found=Notification not found.
test.error.not-found=Test not found.
question.error.not-found=Question not found.
testResult.error.not-found=User Test Result not found.
testProgress.error.not-found=User Test Progress not found.
likedPage.error.not-found=No liked pages.
chapter.error.not-found=Chapter Not Found.
userProgress.error.not-found=User Currently Studying Not Found

pageNo.error.invalid=Invalid page number.
notification.error.notSent=Failed to send push notification.
email.success.mailSent=Successfully sent the email to

file.error.upload=Error uploading file

email.error.notRegistered=Email Not Registered.

subject.success.fetch-details=Subject details fetched successfully
subject.success.fetch-by-id=Lesson fetched successfully by ID

subject.success.create=Subject created successfully.
subject.success.update=Subject updated successfully.
subject.success.delete=Subject deleted successfully.

s3.user-profile-folder=user-profile-images
message.error.inValidOTP=Invalid OTP
message.error.inValidRefreshToken=Please use Valid refresh Token.
message.success.pageMarkedCompleted=Page marked as completed.
message.success.pageAlreadyCompleted=Page already completed.
message.success.topic=Topic already completed.



device.token=Testing123
